import './style.css'
import './cards.css'
import "./game.ts"
//import "./client.ts"
//import "./elements.ts"
import "./mainMenu.ts";
import "./cardCreator.ts";
import "./singleplayerMenu.ts";
import "./roomsMenu.ts";